version: '3'
services:
  redis-master:
    image: bitnami/redis:latest
    container_name: redis-master
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - redis-net
    volumes:
      - redis-master-data:/bitnami/redis/data
      - ./redis-slave.conf:/opt/bitnami/redis/etc/redis.conf
  redis-slave:
    image: bitnami/redis:latest
    container_name: redis-slave
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
    networks:
      - redis-net
    volumes:
      - redis-slave-data:/bitnami/redis/data
      - ./redis-slave.conf:/opt/bitnami/redis/etc/redis.conf
  redis-sentinel:
    image: bitnami/redis-sentinel:latest
    container_name: redis-sentinel
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
    ports:
      - "26379:26379"
    networks:
      - redis-net
    depends_on:
      - redis-master
      - redis-slave
volumes:
  redis-master-data:
  redis-slave-data:
networks:
  redis-net:
